const $=id=>document.getElementById(id);const btn=$("searchBtn");const SELF_TEST=new URLSearchParams(location.search).get("selftest")==="1";
const R8_URL="https://services6.arcgis.com/SKz58fvdFlaEB35q/arcgis/rest/services/survey123_08d14b98657b47309b868f49602375c8_results/FeatureServer/0";
function km(a,b,c,d){const R=6371,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,A=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(A))}
function bearing(a,b,c,d){const p=Math.PI/180,y=Math.sin((d-b)*p)*Math.cos(c*p),x=Math.cos(a*p)*Math.sin(c*p)-Math.sin(a*p)*Math.cos(c*p)*Math.cos((d-b)*p),deg=(Math.atan2(y,x)*180/Math.PI+360)%360,n=["北","北東","東","南東","南","南西","西","北西"];return n[Math.round(deg/45)%8]}
async function fetchR8(){const since=new Date(Date.now()-31*864e5).toISOString().slice(0,10);const q=new URLSearchParams({where:"field_20 >= DATE '"+since+"'",outFields:"objectid,field_7,field_8,field_9,field_17,field_20,field_21,field_26",returnGeometry:"true",outSR:"4326",orderByFields:"field_20 DESC",f:"json"});const r=await fetch(R8_URL+"/query?"+q.toString(),{cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);const j=await r.json();if(j.error)throw new Error(j.error.message||"ArcGIS query error");return (j.features||[]).map(f=>{const x=f.attributes||{},g=f.geometry||{};let t=Number(x.field_20);if(x.field_21&&/^\d{1,2}:\d{2}$/.test(x.field_21)){const d=new Date(t),[hh,mm]=x.field_21.split(":").map(Number);d.setHours(hh,mm,0,0);t=d.getTime()}return{lat:g.y,lon:g.x,seenAt:t,place:[x.field_7,x.field_17].filter(Boolean).join(" "),detail:x.field_9||"",count:x.field_26||"",source:"新潟県公式情報"}}).filter(v=>Number.isFinite(v.lat)&&Number.isFinite(v.lon)&&Number.isFinite(v.seenAt))}
function analyze(lat,lon,data){const now=Date.now(),rows=data.map(v=>({...v,distance:km(lat,lon,v.lat,v.lon),hours:(now-v.seenAt)/36e5,direction:bearing(lat,lon,v.lat,v.lon)})).filter(v=>v.hours>=0);$("r24").textContent=rows.filter(v=>v.hours<=24&&v.distance<=1).length+"件";$("r7").textContent=rows.filter(v=>v.hours<=168&&v.distance<=3).length+"件";$("r30").textContent=rows.filter(v=>v.hours<=720&&v.distance<=5).length+"件";const n=rows.filter(v=>v.hours<=720&&v.distance<=5).sort((a,b)=>a.distance-b.distance)[0];$("nearest").textContent=n?Math.floor(n.hours/24)+"日前・"+n.distance.toFixed(1)+"km・"+n.direction:"30日・5km以内：該当なし";$("nearestDetail").textContent=n?n.place+(n.count?"・"+n.count:"")+" / "+n.source:"";$("results").classList.remove("hidden")}
btn.addEventListener("click",()=>{if(!navigator.geolocation){$("status").textContent="この端末では位置情報を利用できません";return}btn.disabled=true;btn.textContent="現在地を確認中…";$("status").textContent="GPSを取得しています";navigator.geolocation.getCurrentPosition(async p=>{window._acc=p.coords.accuracy;$("status").textContent="公式データを確認しています…";try{const data=await fetchR8();analyze(p.coords.latitude,p.coords.longitude,data);$("status").textContent="現在地・公式データを確認しました（精度 約"+Math.round(window._acc||0)+"m）"}catch(e){console.error(e);$("status").textContent="公式データを取得できませんでした。再度お試しください"}finally{btn.disabled=false;btn.textContent="📍 もう一度サーチ"}},e=>{$("status").textContent=e.code===1?"位置情報の使用が許可されていません":"現在地を取得できませんでした";btn.disabled=false;btn.textContent="📍 周辺をサーチ"},{enableHighAccuracy:true,timeout:12000,maximumAge:0})});
async function runSelfTest(){try{const data=await fetchR8();const now=Date.now(),recent=data.filter(v=>v.seenAt<=now&&now-v.seenAt<=30*864e5).sort((a,b)=>b.seenAt-a.seenAt)[0];if(!recent){$("status").textContent="自己診断：直近30日の公式データが見つかりません";return}analyze(recent.lat,recent.lon,data);$("status").textContent="自己診断OK：公式掲載地点を現在地として検証";btn.textContent="📍 通常の周辺サーチ";btn.addEventListener("click",()=>history.replaceState(null,"",location.pathname));}catch(e){console.error(e);$("status").textContent="自己診断に失敗しました";}}
if(SELF_TEST)runSelfTest();
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));
